cache:
  yarn: true
  directories:
    - node_modules
language: node_js
node_js:
- 9.4.0
install:
  - yarn install
script: cd frontend && yarn run cover --maxWorkers=4 --ci
after_script: cat ./frontend/coverage/lcov.info | ./frontend/node_modules/coveralls/bin/coveralls.js
branches:
  only:
  - master
notifications:
  email: false